### ISSUE TITLE
Deployment failing in python 3.10

### ISSUE THREAD

**Issue by sayanchk** [hyperopt/hyperopt#851]
Hi all,

We have a dependency on hyperopt and the build has started failing recently in python 3.10. Here's the details of the error:

```
    from hyperopt import fmin, tpe, hp, STATUS_OK
/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/hyperopt/__init__.py:39: in <module>
    from .spark import SparkTrials
/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/hyperopt/spark.py:11: in <module>
    from py4j.clientserver import ClientServer
/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/py4j/clientserver.py:12: in <module>
    from collections import deque, Callable
E   ImportError: cannot import name 'Callable' from 'collections' (/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/collections/__init__.py)
```

Looks like this is due to a recent release in py4j (0.10.9.4). We have tested the build and it's working fine in python 3.9.

Is there a plan to officially start supporting hyperopt for python 3.10?
