### ISSUE TITLE
Error with networkx 2.0

### ISSUE THREAD

**Issue by viktorrobin** [hyperopt/hyperopt#346]
Hi,

if you upgrade to networkx 2.0, the following error appears (example from docs):
```bash
best = fmin(objective, space, algo=tpe.suggest, max_evals=100)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/hyperopt/fmin.py", line 314, in fmin
    pass_expr_memo_ctrl=pass_expr_memo_ctrl)
  File "/usr/lib/python2.7/site-packages/hyperopt/base.py", line 786, in __init__
    pyll.toposort(self.expr)
  File "/usr/lib/python2.7/site-packages/hyperopt/pyll/base.py", line 715, in toposort
    assert order[-1] == expr
TypeError: 'generator' object has no attribute '__getitem__'
```
All works fine with networkx 1.11

**Comment by DexHunter** [comment]
What about #333 and #319 ? Maybe you need to check the issue before posting?

**Comment by viktorrobin** [comment]
@DexHunter Deepest apologies for that. For some reasons I missed them.

Closing see  #333 and #319
